def check(stl):
	for i in range (26):
		newStr = ""
		array = []
		for j in stl:
			if ord(j)+i > 122:
				num = ord(j)+i-26
			else:
				num = ord(j)+i
			array.append(chr(num))
		print "".join(array)

check("pdaodwzkskbpdaikkjosalpwynkoopdachkxabnkidkjcgkjcpkpdapatwolwjdwjzhawownwnawjjqhwnokhwnayheloaxacwjikjzwuiknjejcejwoewwjzpnwranoazpdalwyebeypdaoqjwllawnazwowpdejnejcxadejzpdaikkjpklaklhaejwjwnnkslwpdwhkjcpdayajpankbpdapnwygsdeydxacwjejokqpdanjydejwdawruyhkqzokxoyqnazpdareasejdkjcgkjcxqpnaoezajpokbpkgukwjzkpdanyepeaosanawxhapkcapwolaypwyqhwnreasbknwxkqpbkqniejqpaownkqjzoarajpdenpupskwiikjzwuoetpdenpupskliapoqjzwuarajposanadahzwpoydkkhowjziqoaqioejfwlwjsdehaiwjuiknalaklhapkkgejpdaqjqoqwhwopnkjkieywharajpwpdkiaknkjopnaapyknjanowbpansdevvejcwynkoopdalwyebeypdaodwzksaiancazkranjknpdanjywhebknjewwjzokqpdanjknackjsdanapdkqowjzokblaklhawppajzazlwnpeaopkswpydpdaarajppdabenoppkwllawnejpdaqjepazopwpaooejyajejapaajjejapubkqnatlanposwnjazpdwpdklabqhreasanoodkqhzjkplaanqlwppdaogusepdkqpolayewhreasejcamqeliajpoejyahkkgejcwppdaoqjsepdpdajwgazauaywjywqoaxhejzjaoozanagnwhopkjwlnkbaooekjwhldkpkcnwldanowezdaqoazwsahzejcbehpanpkywlpqnawzenaypreaskbayheloaejpdabkkpdehhowxkraknkrehhaywhebknjewdaodwnazpdaldkpkkjyjjenalknpjkpejcpdanwpdanoheioswpdkbpdachkxasdkykqhzoaapdaeilwypkbpdaayheloanwhopkjowezdaswjpazpkajwxhapdanaopkbpdasknhzpkoaadksyhawnephkkgazpkpdkoakbqosdksanabknpqjwpaajkqcdpkoaaeppdaoherankboqjodejapdajpnwrahazokqpdawopwynkooyajpnwhjarwzwokqpdanjqpwdwjzjknpdanjwnevkjwwjzpdajjasiateykeplwooazkranwhxqmqanmqajasiateykwxkqpoarajpdenpubkqnlijejapdenpubkqnliapxabknalapanejckqpawopkbhqxxkygpatwowyyknzejcpkjwow")